apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: jenkins
namespace: jenkins
# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: jenkins

resources:
- deployment.yaml
- service.yaml
- serviceAccount.yaml
- volume.yaml